name: smartfarmtomato
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.3
  firebase_database: ^10.3.4
  intl: ^0.18.1
  fl_chart: ^0.66.2
  provider: ^6.1.5+1
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.5.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  url_launcher: ^6.1.14
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/walpapers.jpeg
    - images/